### ISSUE TITLE
Incorrect LICENSE statements

### ISSUE THREAD

**Issue by rossburton** [ZoranStojsavljevic/meta-socketCAN#3]
The recipes all say that the recipes are `LICENSE="MIT"` and point to the canonical MIT license text in oe-core as the license statement.

This is incorrect.

For example `candump.c` in `can-utils` is GPLv2-only _or_ BSD:

https://github.com/linux-can/can-utils/blob/master/candump.c

And `cansequence.c` is GPLv2-only:

https://github.com/linux-can/can-utils/blob/master/cansequence.c

`LICENSE` is the license of the binaries being distributed, not the recipe text itself.

**Comment by ZoranStojsavljevic** [comment]
Fixed. As per your advise.

commit 71017ca6045c16e327f3dd978a8add4d7f7387cb (HEAD -> master, origin/master, origin/HEAD)
Author: Zoran Stojsavljevic <zoran.s@l4b-software.com>
Date:   Thu Dec 1 15:40:14 2022 +0100

Thank you for pointing this license inconsistencies to me.

Zee
_______
